theme: jekyll-theme-minimal
title: EnduroLogger
description: 'A highly-flexible and modular scientific logging system for the modern era.'
logo: '/assets/images/el.png'
show_downloads: False
google_analytics: 'UA-137881521-1'
